### ISSUE TITLE
Erroneous error message - invalid email address

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#14]
Received an 'invalid email address' message after entering email and then clicking on the start deposition button. Email was correct and when hit the start deposition button again deposition did start.

**Comment by jonwedell** [comment]
This is because it attempts to check with the mail server to see if the e-mail exists before allowing it. It significantly reduces the chances of a typo in the e-mail.

Options:

1. Remove the validation, get more potential typos in emails
2. Increase the timeout - would potentially avoid the issue you encountered, but could also make the interface wait longer in the case the e-mail is invalid
3.  Do nothing, expect the user to press 'new deposition' a second time

My preference is option 2.

**Comment by elulrich** [comment]
Option 2 seems appropriate. What is the current timeout set at?

**Comment by dmaziuk** [comment]
**note** that if it's checking by opening an SMTP connection, it can potentially firewall itself off by opening too many too fast. It's unlikely but Murphy's Law tends to win every time.

**Comment by jonwedell** [comment]
[Increased timeout to 3 seconds.](https://github.com/uwbmrb/BMRB-API/commit/f2ef750c7e72d6fcc4bab1d02bb0e13c82c9f2b7)

**Comment by jonwedell** [comment]
> **note** that if it's checking by opening an SMTP connection, it can potentially firewall itself off by opening too many too fast. It's unlikely but Murphy's Law tends to win every time.

True, and though rare that could cause someone to either
1. have to use a different e-mail
2. have to wait a bit and try again

Which I'm okay with, given how rare it will happen. Are you suggesting the validation isn't worth it because of that risk? I don't believe there is a reliable way to detect this is happening and just allow the user through.

Nobody has ever complained about the validation on the CS-Rosetta server, so hopefully it hasn't happened yet in practice.

**Comment by jonwedell** [comment]
The 3 second timeout should resolve this issue. Closing for now - but we can reopen if student testers or others encounter it again.
