### ISSUE TITLE
In software, software name enumeration list not available

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#2]
Software name field has an enumeration in the dictionary that should be available to the depositor to select from. They should also be able to enter something that is not in the enumerated list.

http://dev-bmrbdep.bmrb.wisc.edu/entry/cdb49f48-349e-4776-867f-996b975c9552/saveframe/software/category

**Comment by jonwedell** [comment]
Fixed in 93b91d4. Fix deployed to testing.

Turns out that if a tag had enumeration ties, only those were used and the default enumerations were ignored. Now the two are concatenated. I put the enumeration ties enumerations at the end rather than the beginning of the new list. Is that reasonable? @elulrich 

A question though: why would the software name be an enumeration tie? Is it used somewhere else? Because suggesting an identical sf_framecode name when they create a new software saveframe isn't helpful.

**Comment by jonwedell** [comment]
Hongyang suggested putting the custom enumerations based on entered data prior to the default enumerations, so I've made the change. It may be worth considering this behavior further.

Ideally we want people to choose the enumeration rather than something they typed in that is slightly different than the enumeration. So for software, it would make sense to put the enumerations first.

But for something like "molecule common name" it makes more sense to put the user entered values first.

Molecule common name
--


"

**Comment by perzeus** [comment]
Can user entered values be checked against enumerations? Kind of like Google’s “did you mean…”
If this is too complex, I would probably prefer make the user select from the enumeration. Of course, previously selected enumeration items could be carried over so as to avoid redundant or multiple  selections of the same items.

Pedro

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jonwedell** [comment]
> Can user entered values be checked against enumerations?

I could probably fix capitalization issues automatically, and I think this is a good idea.

We have two different enumeration types, open and closed enumerations. The closed ones already limit the users to the pre-defined values, so it isn't a problem for those types of tags. It is only for tags where users can enter their own value (or choose a provided one) that this issue appears. So, for example in the software package name - it's possible they have a new software package, so we can't limit them to just the enumerations.

An example of the two cases where we would want the enumerations either first or last:

1) Molecule common name - we want to put the previously user-entered molecule name first, before other enumerated potential molecule names. It's unlikely they are typing something in that is in the enumerated list.
2) Software name - in this case they are probably using a software package we do already have in the enumeration, and so it would be best to suggest the defined enumerations before other software packages they have manually typed in.

Unless we want to capture additional information in the dictionary to specify which it should be for each tag (I don't think that is worth it) we'll have to just pick the one we think makes sense in the most places.

**Comment by jonwedell** [comment]
> I could probably fix capitalization issues automatically

Implemented in c1d580a.

**Comment by jonwedell** [comment]
This has been fixed in bdc3ad5 and bf3051c.
