### ISSUE TITLE
Pre-fill issue with Molecular entity and Molecular assembly

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#58]
When you do either of the pre-fill options it changes the Sf_framecode of the assembly to whatever the name of the assembly is. In the three entries I tested two of them had it where the entity and assembly both had the same Sf_framecode's so it kept bringing up an error. To fix it I changed the assembly name, but noticed that you cannot change the entity name. Every time I tried to change it it would restore itself to whatever was in the reference entry. I think this has something to do with the fix implemented in issue #49 .

**Comment by jonwedell** [comment]
> When you do either of the pre-fill options it changes the Sf_framecode of the assembly to whatever the name of the assembly is.

This is coded this way on purpose: the intention was that when linking experiments to sample conditions, etc., maintaining the same framecodes is better than replacing them all with generic ones.

> In the three entries I tested two of them had it where the entity and assembly both had the same Sf_framecode's so it kept bringing up an error. 

This is definitely a bug - I'm tracking it here: https://github.com/uwbmrb/BMRB-API/issues/48

> Every time I tried to change it it would restore itself to whatever was in the reference entry. I think this has something to do with the fix implemented in issue #49 .

Indeed, I believe you are correct. This should be fixed once #51 is implemented.

**Comment by jonwedell** [comment]
This should be fixed with the newest changes.

Framecodes are now assigned to default values and not changeable at all by the user. Instead the interface shows the value of the "Name" tag of a saveframe, and then sets the appropriate framecode upon selection.

This fixes the duplicate framecode issue on new depositions created from existing entries. @rsiegl - Please confirm - and feel free to close the issue if confirmed.

**Comment by rsiegl** [comment]
I can confirm this is fixed
