### ISSUE TITLE
Opening page entry start order

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#64]
The two most common entry points for depositions are: Start a new clean deposition and Resume a deposition, yet these are at the bottom of the page. I would suggest put 'Click here to start a new deposition from scratch at the top and clearly highlighted. Follow with Resume deposition, followed by starting a deposition from a released or uploaded NMR-STAR file.

**Comment by jonwedell** [comment]
Significant changes to start page in 4b8cda2.

**Comment by jonwedell** [comment]
Thinking about the home page and how to improve it lead me to the following conclusion: It is not at all convenient for users to have to keep a "restore/deposition ID" saved somewhere. In ADIT the user would go to the initial e-mail, get the session ID, paste it into the ADIT web site, and then get to their session. We can do much better. In the new server, all the user has to do is go to the initial e-mail and click the link to return to their session. Therefore I have hid the deposition ID from the initial e-mail entirely, and added more instructions on how to access their entry.

If the user has lost access to that original e-mail, then they have also lost access to the deposition ID. So there is no need to ever expose it to the user, not prompt for it. I have added a link to e-mail us if they have lost their e-mail. (This is what the user would have to do if they lost their e-mail/deposition ID as well.)

For sake of helping users differentiate between multiple simultaneous depositions, I require them to specify a brief nickname for the deposition, so that when they go to their e-mail to resume the deposition they can tell which one is which.

To simplify the new deposition flow, I've hidden the "upload file" and "existing BMRB ID" sections unless the depositor has chosen them in the drop-down menu at the top of the page.

It is still my intention to

1. Add a link to a help page that contains some of the same information that crowds the initial home screen of ADIT.
2. Make the page "prettier" by using Angular Material CSS rules. This will make the form element sizes and layouts look nicer, but I do no intend to significantly change the overall flow of this page.

**Comment by rsiegl** [comment]
Another thing that could be done, which may be way more work than it is worth, would be to have the user create a password for their email. The user could then "log on" and see all the entries they are working on in a table that would have: their quick description, date created, date last accessed, deposition and possibly other information that would be relevant. Then they would not need to retain any of their deposition emails after verifying the email only one time. They could also access all of their entries with ease (possibly even see the current status of their entry once they submit it too), but as I said that may be a lot more work.

**Comment by elulrich** [comment]
Great idea. This is one of the intents for capturing an ORCHID. This ID can be used to do pretty much what you are suggesting.

**Comment by jonwedell** [comment]
I agree that giving a dashboard of in-progress entries would be useful, and it should be fairly straightforward, though time consuming, to implement. Great suggestion.

Personally I would prefer to avoid users having to set and remember/store an additional password. I think we could have the same functionality but have it work in the following way:

1. User clicks "view my depositions" button and provides their e-mail. (Either directly on the home page or on a special "view depositions" page.
2. If any depositions exist with the specified e-mail, send the e-mail a one-time-use link that takes them to a page where they can see the status of all their entries. This page will work for some fixed number of hours (or we could add a cookie to make it last longer).

The benefits of this approach over a password:

1. It requires you control the e-mail address in order to view depositions for that e-mail. Unlike a password it would be much harder for others to get illicit access to your depositions, as they would need to compromise your e-mail account.
2. No need to sign up / create an additional password.
3. Optionally, we could set up the system to allow **any contact author** to view depositions associated with their email address, and not just the primary depositor.

I suggested this approach to the wwPDB team at our last meeting and it is the approach they are implementing in OneDep.
